/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: authController
 * Nominal tests: 7
 * Fault tests: 0
 * Total: 7
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("authController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] registerCustomer - happy path", async () => {
    const res = await request(app)
      .post("/api/auth/register/customer")
      .set('Content-Type', 'application/json')
      .send({
  "username": "generated_customer",
  "email": "generated_customer@example.com",
  "full_name": "Generated Customer",
  "phone": "0901234567",
  "address": "1 Nguyen Trai",
  "password": "password123"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] registerStaff - happy path", async () => {
    const res = await request(app)
      .post("/api/auth/register/staff")
      .set('Content-Type', 'application/json')
      .send({
  "username": "generated_staff",
  "email": "generated_staff@example.com",
  "full_name": "Generated Staff",
  "phone": "0901234567",
  "password": "password123",
  "role": "staff"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] login - happy path", async () => {
    const res = await request(app)
      .post("/api/auth/login")
      .set('Content-Type', 'application/json')
      .send({
  "username": "generated_user",
  "password": "password123"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getMe - happy path", async () => {
    const res = await request(app)
      .get("/api/auth/me")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateProfile - happy path", async () => {
    const res = await request(app)
      .put("/api/auth/update-profile")
      .set('Content-Type', 'application/json')
      .send({
  "full_name": "Updated User",
  "email": "updated_user@example.com",
  "phone": "0901234567",
  "address": "1 Nguyen Trai"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] changePassword - happy path", async () => {
    const res = await request(app)
      .put("/api/auth/change-password")
      .set('Content-Type', 'application/json')
      .send({
  "current_password": "password123",
  "new_password": "password456"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] verifyToken - happy path", async () => {
    const res = await request(app)
      .post("/api/auth/verify-token")
      .set('Content-Type', 'application/json')
      .send({
  "token": "generated.jwt.token"
});

    expect([200, 201, 204]).toContain(res.status);
  });
});
