/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: cartController
 * Nominal tests: 11
 * Fault tests: 0
 * Total: 11
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("cartController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getCartByCustomer - happy path", async () => {
    const res = await request(app)
      .get("/api/carts/customer/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getAllCarts - happy path", async () => {
    const res = await request(app)
      .get("/api/carts/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCartById - happy path", async () => {
    const res = await request(app)
      .get("/api/carts/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] addItemToCart - happy path", async () => {
    const res = await request(app)
      .post("/api/carts/507f1f77bcf86cd799439012/items")
      .set('Content-Type', 'application/json')
      .send({
  "product_id": "507f1f77bcf86cd799439014",
  "quantity": 1
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateItemQuantity - happy path", async () => {
    const res = await request(app)
      .put("/api/carts/items/507f1f77bcf86cd799439012/quantity")
      .set('Content-Type', 'application/json')
      .send({
  "quantity": 2
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] removeItemFromCart - happy path", async () => {
    const res = await request(app)
      .delete("/api/carts/items/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] applyPromo - happy path", async () => {
    const res = await request(app)
      .post("/api/carts/507f1f77bcf86cd799439012/apply-promo")
      .set('Content-Type', 'application/json')
      .send({
  "promo_code": "PROMO10"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] removePromo - happy path", async () => {
    const res = await request(app)
      .delete("/api/carts/507f1f77bcf86cd799439012/remove-promo")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] clearCart - happy path", async () => {
    const res = await request(app)
      .delete("/api/carts/507f1f77bcf86cd799439012/clear")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCartStats - happy path", async () => {
    const res = await request(app)
      .get("/api/carts/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] checkoutCart - happy path", async () => {
    const res = await request(app)
      .patch("/api/carts/507f1f77bcf86cd799439012/checkout")
      .set('Content-Type', 'application/json')
      .send({
  "customer_id": "507f1f77bcf86cd799439012",
  "cart_id": "507f1f77bcf86cd799439013"
});

    expect([200, 201, 204]).toContain(res.status);
  });
});
