/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: customerController
 * Nominal tests: 10
 * Fault tests: 13
 * Total: 23
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("customerController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllCustomers - happy path", async () => {
    const res = await request(app)
      .get("/api/customers")
      .set('Content-Type', 'application/json')
      .query({
  "page": 1,
  "limit": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createCustomer - happy path", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCustomerById - happy path", async () => {
    const res = await request(app)
      .get("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateCustomer - happy path", async () => {
    const res = await request(app)
      .put("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteCustomer - happy path", async () => {
    const res = await request(app)
      .delete("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "reason": "xxxxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCustomerByAccount - happy path", async () => {
    const res = await request(app)
      .get("/api/customers/account/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCustomerStats - happy path", async () => {
    const res = await request(app)
      .get("/api/customers/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updatePoints - happy path", async () => {
    const res = await request(app)
      .patch("/api/customers/507f1f77bcf86cd799439012/points")
      .set('Content-Type', 'application/json')
      .send({
  "pointsToAdd": -10000
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateTotalSpent - happy path", async () => {
    const res = await request(app)
      .patch("/api/customers/507f1f77bcf86cd799439012/spent")
      .set('Content-Type', 'application/json')
      .send({
  "amount": 0
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCustomerOrders - happy path", async () => {
    const res = await request(app)
      .get("/api/customers/507f1f77bcf86cd799439012/orders")
      .set('Content-Type', 'application/json')
      .query({
  "page": 1,
  "limit": 10,
  "status": "pending"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] createCustomer - missing:name", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] createCustomer - missing:email", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] createCustomer - missing:phone", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Invalid email format
  test("[FAULT-F4] createCustomer - format:email on email", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "not-an-email",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Pattern violation: ^[0-9]{10}$
  test("[FAULT-F4] createCustomer - format:undefined on phone", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "invalid_value",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Enum violation: expected one of [Standard, Gold, Silver]
  test("[FAULT-F5] createCustomer - enum on membershipType", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "__invalid_enum__",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Enum violation: expected one of [active, inactive, pending]
  test("[FAULT-F5] createCustomer - enum on status", async () => {
    const res = await request(app)
      .post("/api/customers")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "__invalid_enum__"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Invalid email format
  test("[FAULT-F4] updateCustomer - format:email on email", async () => {
    const res = await request(app)
      .put("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "not-an-email",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Pattern violation: ^[0-9]{10}$
  test("[FAULT-F4] updateCustomer - format:undefined on phone", async () => {
    const res = await request(app)
      .put("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "invalid_value",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Enum violation: expected one of [Standard, Gold, Silver]
  test("[FAULT-F5] updateCustomer - enum on membershipType", async () => {
    const res = await request(app)
      .put("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "__invalid_enum__",
  "age": 18,
  "status": "active"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Enum violation: expected one of [active, inactive, pending]
  test("[FAULT-F5] updateCustomer - enum on status", async () => {
    const res = await request(app)
      .put("/api/customers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "email": "test@example.com",
  "phone": "0901234567",
  "address": "xxxxx",
  "membershipType": "Standard",
  "age": 18,
  "status": "__invalid_enum__"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] updatePoints - missing:pointsToAdd", async () => {
    const res = await request(app)
      .patch("/api/customers/507f1f77bcf86cd799439012/points")
      .set('Content-Type', 'application/json');

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] updateTotalSpent - missing:amount", async () => {
    const res = await request(app)
      .patch("/api/customers/507f1f77bcf86cd799439012/spent")
      .set('Content-Type', 'application/json');

    expect([400, 422]).toContain(res.status);
  });
});
