/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: damagedProductController
 * Nominal tests: 5
 * Fault tests: 0
 * Total: 5
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("damagedProductController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getDamagedProductStats - happy path", async () => {
    const res = await request(app)
      .get("/api/damaged-products/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getDamagedProductsByProductId - happy path", async () => {
    const res = await request(app)
      .get("/api/damaged-products/product/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] adjustInventoryForDamaged - happy path", async () => {
    const res = await request(app)
      .put("/api/damaged-products/507f1f77bcf86cd799439012/adjust-inventory")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getDamagedProductShelves - happy path", async () => {
    const res = await request(app)
      .get("/api/damaged-products/507f1f77bcf86cd799439012/shelves")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] bulkUpdateStatus - happy path", async () => {
    const res = await request(app)
      .put("/api/damaged-products/bulk/update-status")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });
});
