/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: deliveryOrderController
 * Nominal tests: 8
 * Fault tests: 0
 * Total: 8
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("deliveryOrderController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllDeliveryOrders - happy path", async () => {
    const res = await request(app)
      .get("/api/delivery-orders/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createDeliveryOrder - happy path", async () => {
    const res = await request(app)
      .post("/api/delivery-orders/")
      .set('Content-Type', 'application/json')
      .send({
  "order_id": "507f1f77bcf86cd799439015",
  "staff_id": "507f1f77bcf86cd799439016",
  "status": "pending"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getDeliveryOrderById - happy path", async () => {
    const res = await request(app)
      .get("/api/delivery-orders/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateDeliveryOrder - happy path", async () => {
    const res = await request(app)
      .put("/api/delivery-orders/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteDeliveryOrder - happy path", async () => {
    const res = await request(app)
      .delete("/api/delivery-orders/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getDeliveriesByStaff - happy path", async () => {
    const res = await request(app)
      .get("/api/delivery-orders/staff/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getDeliveryStats - happy path", async () => {
    const res = await request(app)
      .get("/api/delivery-orders/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] reassignDelivery - happy path", async () => {
    const res = await request(app)
      .patch("/api/delivery-orders/507f1f77bcf86cd799439012/reassign")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
