/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: feedbackController
 * Nominal tests: 7
 * Fault tests: 9
 * Total: 16
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("feedbackController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllFeedbacks - happy path", async () => {
    const res = await request(app)
      .get("/api/feedbacks/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createFeedback - happy path", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "category": "complaint",
  "subject": "test_value",
  "detail": "test_value",
  "customer_id": "507f1f77bcf86cd799439012",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "507f1f77bcf86cd799439012"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getCustomerFeedbacks - happy path", async () => {
    const res = await request(app)
      .get("/api/feedbacks/customer/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getFeedbackById - happy path", async () => {
    const res = await request(app)
      .get("/api/feedbacks/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateFeedbackStatus - happy path", async () => {
    const res = await request(app)
      .put("/api/feedbacks/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "open",
  "assigned_to_staff_id": "507f1f77bcf86cd799439012"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteFeedback - happy path", async () => {
    const res = await request(app)
      .delete("/api/feedbacks/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getFeedbackStats - happy path", async () => {
    const res = await request(app)
      .get("/api/feedbacks/stats/summary")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] createFeedback - missing:category", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "subject": "test_value",
  "detail": "test_value",
  "customer_id": "507f1f77bcf86cd799439012",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] createFeedback - missing:subject", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "category": "complaint",
  "detail": "test_value",
  "customer_id": "507f1f77bcf86cd799439012",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] createFeedback - missing:customer_id", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "category": "complaint",
  "subject": "test_value",
  "detail": "test_value",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Enum violation: expected one of [complaint, suggestion, praise]
  test("[FAULT-F5] createFeedback - enum on category", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "category": "__invalid_enum__",
  "subject": "test_value",
  "detail": "test_value",
  "customer_id": "507f1f77bcf86cd799439012",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Pattern violation: ^[0-9a-fA-F]{24}$
  test("[FAULT-F4] createFeedback - format:undefined on customer_id", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "category": "complaint",
  "subject": "test_value",
  "detail": "test_value",
  "customer_id": "invalid_value",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Pattern violation: ^[0-9a-fA-F]{24}$
  test("[FAULT-F4] createFeedback - format:undefined on order_id", async () => {
    const res = await request(app)
      .post("/api/feedbacks/")
      .set('Content-Type', 'application/json')
      .send({
  "category": "complaint",
  "subject": "test_value",
  "detail": "test_value",
  "customer_id": "507f1f77bcf86cd799439012",
  "rating": 1,
  "sentiment": "test_value",
  "order_id": "invalid_value"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Missing required field
  test("[FAULT-F3] updateFeedbackStatus - missing:status", async () => {
    const res = await request(app)
      .put("/api/feedbacks/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "assigned_to_staff_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Enum violation: expected one of [open, in_progress, resolved, closed]
  test("[FAULT-F5] updateFeedbackStatus - enum on status", async () => {
    const res = await request(app)
      .put("/api/feedbacks/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "__invalid_enum__",
  "assigned_to_staff_id": "507f1f77bcf86cd799439012"
});

    expect([400, 422]).toContain(res.status);
  });

  // ⚠️ Pattern violation: ^[0-9a-fA-F]{24}$
  test("[FAULT-F4] updateFeedbackStatus - format:undefined on assigned_to_staff_id", async () => {
    const res = await request(app)
      .put("/api/feedbacks/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "open",
  "assigned_to_staff_id": "invalid_value"
});

    expect([400, 422]).toContain(res.status);
  });
});
