/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: invoiceController
 * Nominal tests: 9
 * Fault tests: 0
 * Total: 9
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("invoiceController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllInvoices - happy path", async () => {
    const res = await request(app)
      .get("/api/invoices/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createInvoice - happy path", async () => {
    const res = await request(app)
      .post("/api/invoices/")
      .set('Content-Type', 'application/json')
      .send({
  "customer_id": "507f1f77bcf86cd799439012",
  "items": [
    {
      "product_id": "507f1f77bcf86cd799439014",
      "quantity": 1,
      "price": 15000
    }
  ]
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getInvoiceById - happy path", async () => {
    const res = await request(app)
      .get("/api/invoices/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateInvoice - happy path", async () => {
    const res = await request(app)
      .put("/api/invoices/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteInvoice - happy path", async () => {
    const res = await request(app)
      .delete("/api/invoices/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getInvoicesByCustomer - happy path", async () => {
    const res = await request(app)
      .get("/api/invoices/customer/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getInvoiceStats - happy path", async () => {
    const res = await request(app)
      .get("/api/invoices/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] markAsPaid - happy path", async () => {
    const res = await request(app)
      .patch("/api/invoices/507f1f77bcf86cd799439012/mark-paid")
      .set('Content-Type', 'application/json')
      .send({
  "payment_method": "cash"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getUnpaidInvoices - happy path", async () => {
    const res = await request(app)
      .get("/api/invoices/filter/unpaid")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
