/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: orderController
 * Nominal tests: 9
 * Fault tests: 0
 * Total: 9
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("orderController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllOrders - happy path", async () => {
    const res = await request(app)
      .get("/api/orders/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createOrder - happy path", async () => {
    const res = await request(app)
      .post("/api/orders/")
      .set('Content-Type', 'application/json')
      .send({
  "customer_id": "507f1f77bcf86cd799439012",
  "cart_id": "507f1f77bcf86cd799439013"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getOrderById - happy path", async () => {
    const res = await request(app)
      .get("/api/orders/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateOrder - happy path", async () => {
    const res = await request(app)
      .put("/api/orders/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteOrder - happy path", async () => {
    const res = await request(app)
      .delete("/api/orders/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getOrdersByCustomer - happy path", async () => {
    const res = await request(app)
      .get("/api/orders/customer/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getOrderStats - happy path", async () => {
    const res = await request(app)
      .get("/api/orders/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateOrderItemStatus - happy path", async () => {
    const res = await request(app)
      .patch("/api/orders/507f1f77bcf86cd799439012/items/507f1f77bcf86cd799439012/status")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] cancelOrder - happy path", async () => {
    const res = await request(app)
      .patch("/api/orders/507f1f77bcf86cd799439012/cancel")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
