/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: productBatchController
 * Nominal tests: 2
 * Fault tests: 0
 * Total: 2
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("productBatchController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getBatchesByProduct - happy path", async () => {
    const res = await request(app)
      .get("/api/product-batches/product/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] adjustBatchQuantity - happy path", async () => {
    const res = await request(app)
      .put("/api/product-batches/507f1f77bcf86cd799439012/adjust")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
