/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: productShelfController
 * Nominal tests: 6
 * Fault tests: 0
 * Total: 6
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("productShelfController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getProductShelfStats - happy path", async () => {
    const res = await request(app)
      .get("/api/product-shelves/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getShelvesByProduct - happy path", async () => {
    const res = await request(app)
      .get("/api/product-shelves/product/507f1f77bcf86cd799439012/shelves")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getProductsByShelf - happy path", async () => {
    const res = await request(app)
      .get("/api/product-shelves/shelf/507f1f77bcf86cd799439012/products")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] moveProductToShelf - happy path", async () => {
    const res = await request(app)
      .put("/api/product-shelves/507f1f77bcf86cd799439012/move")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] bulkAssignToShelf - happy path", async () => {
    const res = await request(app)
      .post("/api/product-shelves/bulk/assign")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getProductsForDamagedRecord - happy path", async () => {
    const res = await request(app)
      .get("/api/product-shelves/for-damaged-record")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
