/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: productStockController
 * Nominal tests: 6
 * Fault tests: 0
 * Total: 6
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("productStockController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getProductStockStats - happy path", async () => {
    const res = await request(app)
      .get("/api/product-stocks/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getStockByProduct - happy path", async () => {
    const res = await request(app)
      .get("/api/product-stocks/product/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getStockByShelf - happy path", async () => {
    const res = await request(app)
      .get("/api/product-stocks/shelf/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getLowStockProducts - happy path", async () => {
    const res = await request(app)
      .get("/api/product-stocks/low-stock")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] adjustStockQuantity - happy path", async () => {
    const res = await request(app)
      .put("/api/product-stocks/507f1f77bcf86cd799439012/adjust")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] bulkUpdateStatus - happy path", async () => {
    const res = await request(app)
      .put("/api/product-stocks/bulk/update-status")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });
});
