/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: productController
 * Nominal tests: 13
 * Fault tests: 0
 * Total: 13
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("productController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllProducts - happy path", async () => {
    const res = await request(app)
      .get("/api/products")
      .set('Content-Type', 'application/json')
      .query({
  "page": 1,
  "limit": 10,
  "status": "active",
  "category": "test_value"
})
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getProductStats - happy path", async () => {
    const res = await request(app)
      .get("/api/products/stats")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getLowStockProducts - happy path", async () => {
    const res = await request(app)
      .get("/api/products/low-stock")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getProductsByCategory - happy path", async () => {
    const res = await request(app)
      .get("/api/products/category/test_value")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getProductsBySupplier - happy path", async () => {
    const res = await request(app)
      .get("/api/products/supplier/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getProductById - happy path", async () => {
    const res = await request(app)
      .get("/api/products/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateProduct - happy path", async () => {
    const res = await request(app)
      .put("/api/products/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteProduct - happy path", async () => {
    const res = await request(app)
      .delete("/api/products/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createProduct - happy path", async () => {
    const res = await request(app)
      .post("/api/products/")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] permanentDeleteProduct - happy path", async () => {
    const res = await request(app)
      .delete("/api/products/507f1f77bcf86cd799439012/permanent")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateProductStock - happy path", async () => {
    const res = await request(app)
      .patch("/api/products/507f1f77bcf86cd799439012/stock")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateProductPrice - happy path", async () => {
    const res = await request(app)
      .patch("/api/products/507f1f77bcf86cd799439012/price")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] activateProduct - happy path", async () => {
    const res = await request(app)
      .patch("/api/products/507f1f77bcf86cd799439012/activate")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Product",
  "price": 15000,
  "quantity": 10,
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });
});
