/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: promotionController
 * Nominal tests: 7
 * Fault tests: 0
 * Total: 7
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("promotionController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllPromotions - happy path", async () => {
    const res = await request(app)
      .get("/api/promotions/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createPromotion - happy path", async () => {
    const res = await request(app)
      .post("/api/promotions/")
      .set('Content-Type', 'application/json')
      .send({
  "code": "PROMO10",
  "discount_type": "percentage",
  "discount_value": 10
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getPromotionById - happy path", async () => {
    const res = await request(app)
      .get("/api/promotions/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updatePromotion - happy path", async () => {
    const res = await request(app)
      .put("/api/promotions/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deletePromotion - happy path", async () => {
    const res = await request(app)
      .delete("/api/promotions/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] validatePromoCode - happy path", async () => {
    const res = await request(app)
      .post("/api/promotions/validate")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getApplicablePromotions - happy path", async () => {
    const res = await request(app)
      .get("/api/promotions/applicable")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
