/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: sectionController
 * Nominal tests: 6
 * Fault tests: 0
 * Total: 6
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("sectionController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllSections - happy path", async () => {
    const res = await request(app)
      .get("/api/sections/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createSection - happy path", async () => {
    const res = await request(app)
      .post("/api/sections/")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Section",
  "description": "Generated section for tests"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getSectionById - happy path", async () => {
    const res = await request(app)
      .get("/api/sections/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateSection - happy path", async () => {
    const res = await request(app)
      .put("/api/sections/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteSection - happy path", async () => {
    const res = await request(app)
      .delete("/api/sections/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getShelvesInSection - happy path", async () => {
    const res = await request(app)
      .get("/api/sections/507f1f77bcf86cd799439012/shelves")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
