/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: shelfController
 * Nominal tests: 5
 * Fault tests: 0
 * Total: 5
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("shelfController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getShelfStats - happy path", async () => {
    const res = await request(app)
      .get("/api/shelves/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getShelvesByCategory - happy path", async () => {
    const res = await request(app)
      .get("/api/shelves/category/test_value")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getAvailableShelves - happy path", async () => {
    const res = await request(app)
      .get("/api/shelves/available")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] toggleShelfFull - happy path", async () => {
    const res = await request(app)
      .put("/api/shelves/507f1f77bcf86cd799439012/toggle-full")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getShelfCapacity - happy path", async () => {
    const res = await request(app)
      .get("/api/shelves/507f1f77bcf86cd799439012/capacity")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
