/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: staffController
 * Nominal tests: 9
 * Fault tests: 0
 * Total: 9
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("staffController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllStaff - happy path", async () => {
    const res = await request(app)
      .get("/api/staff/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createStaff - happy path", async () => {
    const res = await request(app)
      .post("/api/staff/")
      .set('Content-Type', 'application/json')
      .send({
  "username": "generated_staff",
  "email": "generated_staff@example.com",
  "full_name": "Generated Staff",
  "phone": "0901234567",
  "password": "password123",
  "role": "staff"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getStaffStats - happy path", async () => {
    const res = await request(app)
      .get("/api/staff/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getStaffById - happy path", async () => {
    const res = await request(app)
      .get("/api/staff/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateStaff - happy path", async () => {
    const res = await request(app)
      .put("/api/staff/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteStaff - happy path", async () => {
    const res = await request(app)
      .delete("/api/staff/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] permanentDeleteStaff - happy path", async () => {
    const res = await request(app)
      .delete("/api/staff/507f1f77bcf86cd799439012/permanent")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] activateStaff - happy path", async () => {
    const res = await request(app)
      .patch("/api/staff/507f1f77bcf86cd799439012/activate")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getStaffByAccountId - happy path", async () => {
    const res = await request(app)
      .get("/api/staff/account/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
