/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: supplierController
 * Nominal tests: 10
 * Fault tests: 0
 * Total: 10
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("supplierController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getAllSuppliers - happy path", async () => {
    const res = await request(app)
      .get("/api/suppliers/")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] createSupplier - happy path", async () => {
    const res = await request(app)
      .post("/api/suppliers/")
      .set('Content-Type', 'application/json')
      .send({
  "name": "Generated Supplier",
  "email": "supplier@example.com",
  "phone": "0901234567",
  "address": "1 Nguyen Trai"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getSupplierStats - happy path", async () => {
    const res = await request(app)
      .get("/api/suppliers/stats")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getActiveSuppliers - happy path", async () => {
    const res = await request(app)
      .get("/api/suppliers/active")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getSupplierById - happy path", async () => {
    const res = await request(app)
      .get("/api/suppliers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] updateSupplier - happy path", async () => {
    const res = await request(app)
      .put("/api/suppliers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json')
      .send({
  "status": "active"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] deleteSupplier - happy path", async () => {
    const res = await request(app)
      .delete("/api/suppliers/507f1f77bcf86cd799439012")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] getSupplierProducts - happy path", async () => {
    const res = await request(app)
      .get("/api/suppliers/507f1f77bcf86cd799439012/products")
      .set('Content-Type', 'application/json')
      .send({
  "name": "xxx",
  "price": 15000,
  "quantity": 10,
  "status": "xxx"
});

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] permanentDeleteSupplier - happy path", async () => {
    const res = await request(app)
      .delete("/api/suppliers/507f1f77bcf86cd799439012/permanent")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] activateSupplier - happy path", async () => {
    const res = await request(app)
      .patch("/api/suppliers/507f1f77bcf86cd799439012/activate")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
