/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: telemetryController
 * Nominal tests: 2
 * Fault tests: 0
 * Total: 2
 */
const request = require('supertest');
require('../../test-generator/generatedTestEnvironment');
const app = require('../../server');

describe("telemetryController generated API suite", () => {

  // ✅ happy path
  test("[NOMINAL] getTraces - happy path", async () => {
    const res = await request(app)
      .get("/api/telemetry/traces")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });

  // ✅ happy path
  test("[NOMINAL] clearTraces - happy path", async () => {
    const res = await request(app)
      .delete("/api/telemetry/traces")
      .set('Content-Type', 'application/json');

    expect([200, 201, 204]).toContain(res.status);
  });
});
