const fs = require('fs');
const path = require('path');

function formatQuery(queryParams) {
  if (!queryParams || Object.keys(queryParams).length === 0) {
    return '';
  }

  return `.query(${JSON.stringify(queryParams, null, 2)})`;
}

function formatBody(body) {
  if (!body || (typeof body === 'object' && Object.keys(body).length === 0)) {
    return '';
  }

  return `.send(${JSON.stringify(body, null, 2)})`;
}

function generateJestFile(controllerName, nominalTests, faultTests, outputPath) {
  const allTests = [...nominalTests, ...faultTests];
  const appImportPath = path.relative(path.dirname(outputPath), path.join(__dirname, '..', 'server'));
  const environmentImportPath = path.relative(path.dirname(outputPath), path.join(__dirname, 'generatedTestEnvironment'));
  const normalizedAppImportPath = appImportPath.replace(/\\/g, '/');
  const normalizedEnvironmentImportPath = environmentImportPath.replace(/\\/g, '/');

  const testBlocks = allTests.map((testCase) => {
    const method = testCase.method.toLowerCase();
    const querySegment = formatQuery(testCase.queryParams);
    const bodySegment = formatBody(testCase.body);
    const statusList = `[${testCase.expectStatus.join(', ')}]`;

    return `
  // ${testCase.faultInfo ? `⚠️ ${testCase.faultInfo}` : '✅ happy path'}
  test(${JSON.stringify(testCase.name)}, async () => {
    const res = await request(app)
      .${method}(${JSON.stringify(testCase.url)})
      .set('Content-Type', 'application/json')${querySegment ? `
      ${querySegment}` : ''}${bodySegment ? `
      ${bodySegment}` : ''};

    expect(${statusList}).toContain(res.status);
  });`;
  }).join('\n');

  const content = `/**
 * AUTO-GENERATED TEST FILE
 * Generated by server/test-generator
 * Do not edit manually.
 *
 * Controller: ${controllerName}
 * Nominal tests: ${nominalTests.length}
 * Fault tests: ${faultTests.length}
 * Total: ${allTests.length}
 */
const request = require('supertest');
require('${normalizedEnvironmentImportPath}');
const app = require('${normalizedAppImportPath}');

describe(${JSON.stringify(`${controllerName} generated API suite`)}, () => {
${testBlocks}
});
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');

  console.log(`\n✅ Generated test file: ${outputPath}`);
  console.log(`   Nominal: ${nominalTests.length} | Fault: ${faultTests.length} | Total: ${allTests.length}`);
}

module.exports = {
  generateJestFile,
};