import React, { useEffect, useState } from "react";
import {
  FiRefreshCw,
  FiCheckCircle,
  FiAlertTriangle,
  FiFileText,
  FiLayers,
  FiClock,
  FiActivity,
  FiDatabase,
  FiPackage,
  FiChevronRight,
} from "react-icons/fi";
import { fetchGeneratedTestMonitorSummary } from "../../../services/generatedTestMonitorService";
import "./OpenApiTestMonitor.css";

const formatNumber = (value) => Number(value || 0).toLocaleString();

const formatPercent = (value) => `${Number(value || 0).toFixed(1)}%`;

const formatDuration = (value) => {
  if (value === null || value === undefined) {
    return "--";
  }

  if (value < 1000) {
    return `${Math.round(value)} ms`;
  }

  return `${(value / 1000).toFixed(2)} s`;
};

const formatDateTime = (value) => {
  if (!value) {
    return "--";
  }

  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "--" : date.toLocaleString();
};

const OpenApiTestMonitor = () => {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState(null);
  const [lastUpdated, setLastUpdated] = useState(null);
  const [selectedSuite, setSelectedSuite] = useState("");

  const loadReport = async (showSpinner = false) => {
    try {
      if (showSpinner || !report) {
        setLoading(true);
      } else {
        setRefreshing(true);
      }

      const data = await fetchGeneratedTestMonitorSummary();
      setReport(data);
      setError(null);
      setLastUpdated(new Date().toLocaleString());

      setSelectedSuite((currentSuite) => {
        const suites = Array.isArray(data?.suites) ? data.suites : [];
        if (suites.some((suite) => suite.controllerName === currentSuite)) {
          return currentSuite;
        }

        const preferredSuite = suites.find((suite) => suite.status === "failed") || suites[0];
        return preferredSuite?.controllerName || "";
      });
    } catch (fetchError) {
      setError(
        fetchError?.message ||
          "Không đọc được snapshot kết quả autogenerated tests. Hãy chạy npm run test:openapi-generated.",
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadReport(true);
    const intervalId = setInterval(() => {
      loadReport(false);
    }, 10000);

    return () => clearInterval(intervalId);
  }, []);

  const summary = report?.summary || {};
  const artifacts = report?.artifacts || {};
  const runMetadata = report?.runMetadata || {};
  const suites = Array.isArray(report?.suites) ? report.suites : [];
  const latestFailures = Array.isArray(report?.latestFailures) ? report.latestFailures : [];
  const selectedSuiteData = suites.find((suite) => suite.controllerName === selectedSuite) || suites[0] || null;
  const passRate = Number(summary.passRate || 0);
  const buildStateLabel = report?.available ? (summary.failedTests > 0 ? "Has failures" : "All green") : "Waiting for snapshot";
  const buildStateTone = report?.available ? (summary.failedTests > 0 ? "warning" : "success") : "neutral";
  const totalSuites = Number(summary.totalSuites || 0);

  const overviewCards = [
    {
      label: "Pass rate",
      value: formatPercent(passRate),
      subtext: `${formatNumber(summary.passedTests)} / ${formatNumber(summary.totalTests)} tests`,
      icon: <FiActivity />,
      tone: passRate >= 80 ? "success" : passRate >= 60 ? "warning" : "danger",
    },
    {
      label: "Passed tests",
      value: formatNumber(summary.passedTests),
      subtext: `${formatNumber(summary.totalTests)} total cases`,
      icon: <FiCheckCircle />,
      tone: "success",
    },
    {
      label: "Failed tests",
      value: formatNumber(summary.failedTests),
      subtext: `${formatNumber(summary.failedSuites)} failed suites`,
      icon: <FiAlertTriangle />,
      tone: summary.failedTests > 0 ? "danger" : "success",
    },
    {
      label: "Generated suites",
      value: formatNumber(summary.totalSuites),
      subtext: `${formatNumber(summary.passedSuites)} suites passing`,
      icon: <FiLayers />,
      tone: "info",
    },
    {
      label: "Controller YAML",
      value: formatNumber(artifacts.controllerYamlCount),
      subtext: "Per-controller OpenAPI specs",
      icon: <FiFileText />,
      tone: "info",
    },
    {
      label: "Generated test files",
      value: formatNumber(artifacts.generatedTestCount),
      subtext: "One Jest suite per controller",
      icon: <FiPackage />,
      tone: "info",
    },
  ];

  if (loading && !report) {
    return (
      <div className="test-monitor-page">
        <div className="test-monitor-shell test-monitor-shell--loading">
          <div className="test-monitor-loader" />
          <p>Loading autogenerated test snapshot...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="test-monitor-page">
      <div className="test-monitor-background test-monitor-background--one" />
      <div className="test-monitor-background test-monitor-background--two" />

      <div className="test-monitor-shell">
        <section className="test-monitor-hero">
          <div className="test-monitor-hero__copy">
            <div className={`status-pill status-pill--${buildStateTone}`}>
              <span className="status-pill__dot" />
              {buildStateLabel}
            </div>
            <h1>OpenAPI Test Monitor</h1>
            <p>
              Theo dõi kết quả tạo test case tự động từ comment <span>@openapi</span>,
              số suite sinh ra và trạng thái pass/fail sau mỗi lần chạy Jest.
            </p>
            <div className="hero-meta-row">
              <span>
                <FiClock /> Last updated: {lastUpdated || formatDateTime(runMetadata.endTime)}
              </span>
              <span>
                <FiDatabase /> Snapshot: {report?.available ? "Available" : "Missing"}
              </span>
              <span>
                <FiFileText /> Command: <strong>npm run test:openapi-generated</strong>
              </span>
            </div>
          </div>

          <div className="test-monitor-hero__panel">
            <div className="hero-panel__header">
              <div>
                <span className="hero-panel__label">Current run</span>
                <strong>{report?.available ? "Live snapshot from openapi-results.json" : "Awaiting first run"}</strong>
              </div>
              <button
                type="button"
                className="test-monitor-refresh"
                onClick={() => loadReport(false)}
                disabled={refreshing}
              >
                <FiRefreshCw className={refreshing ? "spin" : ""} />
                Refresh
              </button>
            </div>

            <div className="hero-panel__stats">
              <div>
                <span>Total suites</span>
                <strong>{formatNumber(totalSuites)}</strong>
              </div>
              <div>
                <span>Failed suites</span>
                <strong>{formatNumber(summary.failedSuites)}</strong>
              </div>
              <div>
                <span>Runtime errors</span>
                <strong>{formatNumber(summary.runtimeErrorSuites)}</strong>
              </div>
              <div>
                <span>Open handles</span>
                <strong>{formatNumber(runMetadata.openHandlesCount)}</strong>
              </div>
            </div>
          </div>
        </section>

        {error && (
          <div className="test-monitor-alert">
            <strong>Cannot refresh snapshot.</strong>
            <span>{error}</span>
          </div>
        )}

        <section className="overview-grid">
          {overviewCards.map((card) => (
            <article key={card.label} className={`overview-card overview-card--${card.tone}`}>
              <div className="overview-card__icon">{card.icon}</div>
              <div className="overview-card__content">
                <span>{card.label}</span>
                <strong>{card.value}</strong>
                <p>{card.subtext}</p>
              </div>
            </article>
          ))}
        </section>

        <section className="content-grid">
          <div className="panel panel--wide">
            <div className="panel__header">
              <div>
                <span className="panel__eyebrow">Generated suites</span>
                <h2>Pass rate theo controller</h2>
              </div>
              <span className="panel__badge">{formatNumber(suites.length)} suites tracked</span>
            </div>

            <div className="suite-list">
              {suites.map((suite) => {
                const isActive = suite.controllerName === selectedSuite;
                const suiteTone = suite.status === "failed" ? "danger" : "success";

                return (
                  <button
                    key={suite.controllerName}
                    type="button"
                    className={`suite-card suite-card--${suiteTone} ${isActive ? "suite-card--active" : ""}`}
                    onClick={() => setSelectedSuite(suite.controllerName)}
                  >
                    <div className="suite-card__top">
                      <div>
                        <strong>{suite.controllerName}</strong>
                        <span>{formatNumber(suite.totalTests)} tests</span>
                      </div>
                      <div className={`suite-status suite-status--${suiteTone}`}>
                        {suite.status}
                      </div>
                    </div>

                    <div className="suite-card__bar">
                      <span style={{ width: `${Math.max(suite.passRate, 2)}%` }} />
                    </div>

                    <div className="suite-card__meta">
                      <span>{formatPercent(suite.passRate)}</span>
                      <span>
                        <FiClock /> {formatDuration(suite.durationMs)}
                      </span>
                      <span>
                        <FiAlertTriangle /> {formatNumber(suite.failedTests)} failed
                      </span>
                    </div>
                  </button>
                );
              })}

              {suites.length === 0 && (
                <div className="empty-state">
                  No generated suite snapshot yet. Run the autogenerated test command to populate this view.
                </div>
              )}
            </div>
          </div>

          <div className="panel">
            <div className="panel__header">
              <div>
                <span className="panel__eyebrow">Selected suite</span>
                <h2>{selectedSuiteData?.controllerName || "No suite selected"}</h2>
              </div>
              {selectedSuiteData && (
                <span className={`suite-status suite-status--${selectedSuiteData.status === "failed" ? "danger" : "success"}`}>
                  {selectedSuiteData.status}
                </span>
              )}
            </div>

            {selectedSuiteData ? (
              <div className="detail-stack">
                <div className="detail-summary">
                  <div>
                    <span>Tests</span>
                    <strong>{formatNumber(selectedSuiteData.totalTests)}</strong>
                  </div>
                  <div>
                    <span>Passed</span>
                    <strong>{formatNumber(selectedSuiteData.passedTests)}</strong>
                  </div>
                  <div>
                    <span>Failed</span>
                    <strong>{formatNumber(selectedSuiteData.failedTests)}</strong>
                  </div>
                  <div>
                    <span>Pass rate</span>
                    <strong>{formatPercent(selectedSuiteData.passRate)}</strong>
                  </div>
                </div>

                <div className="detail-meta">
                  <div>
                    <span>Started</span>
                    <strong>{formatDateTime(selectedSuiteData.startTime)}</strong>
                  </div>
                  <div>
                    <span>Ended</span>
                    <strong>{formatDateTime(selectedSuiteData.endTime)}</strong>
                  </div>
                  <div>
                    <span>Duration</span>
                    <strong>{formatDuration(selectedSuiteData.durationMs)}</strong>
                  </div>
                </div>

                <div className="failure-stack">
                  <div className="failure-stack__header">
                    <h3>Failing assertions</h3>
                    <span>{formatNumber(selectedSuiteData.failures?.length || 0)} items</span>
                  </div>

                  {(selectedSuiteData.failures || []).length > 0 ? (
                    selectedSuiteData.failures.map((failure) => (
                      <div key={`${selectedSuiteData.controllerName}-${failure.title}`} className="failure-item">
                        <strong>{failure.title}</strong>
                        <pre>{failure.message}</pre>
                      </div>
                    ))
                  ) : (
                    <div className="success-message">
                      Suite này đang xanh hoàn toàn. Không có assertion fail nào trong snapshot gần nhất.
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="empty-state">
                Chọn một controller ở danh sách bên trái để xem chi tiết.
              </div>
            )}
          </div>
        </section>

        <section className="content-grid content-grid--bottom">
          <div className="panel">
            <div className="panel__header">
              <div>
                <span className="panel__eyebrow">Latest failures</span>
                <h2>Failures gần nhất trong toàn bộ run</h2>
              </div>
              <span className="panel__badge">{formatNumber(latestFailures.length)} recorded</span>
            </div>

            <div className="latest-failure-list">
              {latestFailures.length > 0 ? (
                latestFailures.map((failure, index) => (
                  <div key={`${failure.controllerName}-${index}`} className="latest-failure-item">
                    <div className="latest-failure-item__title">
                      <strong>{failure.controllerName}</strong>
                      <FiChevronRight />
                    </div>
                    <span>{failure.title}</span>
                    <pre>{failure.message}</pre>
                  </div>
                ))
              ) : (
                <div className="success-message">
                  Run gần nhất không ghi nhận assertion fail nào.
                </div>
              )}
            </div>
          </div>

          <div className="panel">
            <div className="panel__header">
              <div>
                <span className="panel__eyebrow">Snapshot data</span>
                <h2>Artifacts & run metadata</h2>
              </div>
            </div>

            <div className="artifact-grid">
              <div className="artifact-card">
                <span>Results file</span>
                <strong>{artifacts.resultsFile || "generated-tests/openapi-results.json"}</strong>
              </div>
              <div className="artifact-card">
                <span>Generated tests path</span>
                <strong>{artifacts.generatedTestsPath || "generated-tests/openapi-generated"}</strong>
              </div>
              <div className="artifact-card">
                <span>Run success</span>
                <strong>{runMetadata.success ? "true" : "false"}</strong>
              </div>
              <div className="artifact-card">
                <span>Snapshot updated</span>
                <strong>{formatDateTime(report?.generatedAt)}</strong>
              </div>
            </div>

            <div className="note-card">
              The page refreshes automatically every 10 seconds and always reads the latest
              Jest JSON snapshot produced by <strong>npm run test:openapi-generated</strong>.
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default OpenApiTestMonitor;